# Generated by Django 2.1.7 on 2019-03-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0004_auto_20190319_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
